argo-cd:
  server:
    service:
      type: ClusterIP
  networkPolicy:
    enabled: false
  configs:
    cm:
      url: "https://argocd.homelab.local"
      oidc.config: |
        name: Keycloak
        issuer: https://keycloak.homelab.local/realms/homelab
        clientID: argocd
        clientSecret: $oidc.keycloak.clientSecret
        requestedScopes:
          - openid
          - profile
          - email
          - groups
        rootCA: |
          -----BEGIN CERTIFICATE-----
          MIIDQTCCAimgAwIBAgIUE5zxpMbBAAU+TqetfIbrBK+jSvkwDQYJKoZIhvcNAQEL
          BQAwGjEYMBYGA1UEAxMPaG9tZWxhYi1yb290LWNhMB4XDTI2MDQyNzIwNDkzNVoX
          DTM2MDQyNDIwNTAwNVowGjEYMBYGA1UEAxMPaG9tZWxhYi1yb290LWNhMIIBIjAN
          BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8YZ+TYFVym1hXWJdR/Qse8gmZrFV
          3mZ155KPYai+UgbQdwXm/fM1iT4wy1KicjnLWzMPiGNrvIAWOoIQljC/A9SvBdLE
          5SVIU5vVS7Xfw9WcfFd7WlOmr1CQ5tnwzMmN2vbnAzRjPCUh4jPbQ5ze03prXcyb
          1d0/hYhcOy0tWrlVxuTW72egwuK64q3jIfjFQYZmBmca2nhkDi+VlRRiuOWMvFSN
          9W5YUOFlD4hJVRTNvwQV9zVCDjxk3bAFNXPeZFTsfP9ZiVxVG1pO11KrKbUaVBx1
          EpKefpQPKThOfyk9k4F2AkE0KdQmTSAgY6Yv3iBXQ1T/hT/Gh0qVizsvoQIDAQAB
          o38wfTAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU
          I6C2vkQe2XAKtz97u2pv7w5Z+FEwHwYDVR0jBBgwFoAUI6C2vkQe2XAKtz97u2pv
          7w5Z+FEwGgYDVR0RBBMwEYIPaG9tZWxhYi1yb290LWNhMA0GCSqGSIb3DQEBCwUA
          A4IBAQDqsw3nu363Jt1puGpzXwiHDfkS+1S2QNGeHJrQx3XA0YmraygvOLHolTmq
          FdSxA9mcFixU7dwc29EFrl9IcCxkrS1Z+qknR8L2HCyHnJOGO95zrjUcrEE/fEeL
          uoVxdnobmd25VSHdi37xySp53AW65ftwNw6E0+YwBS7eOuAatlJ7wJK/APGR78n9
          nVBqwjJkm/UaaTyCcaT6CuZjMXbOr2Wfb6U9dbdDGDo57VimdcgMrLC1VJlalf7h
          4oQI6dtbLaDrdbraFNGvnHWUqxA97MfX7+CguORzaUJBPfDwnRSqzG0PWmuJ2O+w
          izPKf6fif0UHT2F2HdS9EBqMy+3e
          -----END CERTIFICATE-----
    rbac:
      policy.default: role:readonly
      policy.csv: |
        g, homelab-admins, role:admin
        g, homelab-viewers, role:readonly
    params:
      server.insecure: "true"