---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: falcosidekick-splunk
  namespace: falco
spec:
  encryptedData:
    splunk-token: AgCgMgui0Z0l7zcBZy+YPVTVdXo4Wvzv3HMYx56jxb80sosAZ+WwwLt5Ywozv2dX3LDo8OcYqODdaY8rRnKFcWGYV8h9PrLSRuuY8Q7zwvVTZl1iCrGMaVvcnDvisEaNv/ARimjonVgJfVMBafDi5pdPidI1eCy/z9KFa/D6pCQHlII4ECMMLHRJGa6WpSrA5ihhP3C2YnxIqJP8okbya8w7s/xiUp+hr0iOsCLP5S8pnjTRDuITwqALh7wX8OjeRmLSMF0NA/rD9IaffY+b1Kfwko5UWji8m8KkId3VvdBIiNWwgxwsRBQif8p7HCUR9oUd7kA48qeEbW8bZAtDmsVIhDb5uI/5dqkvxmRLa6C+sOKPKDKwZW1lViG+YtaNPSBBeJeqi7kQjgB5B5jS8lWrDIyyTH4zSuWippgCkhxIzANDJH38gJfgViKY7oYNr7digEdnFH509xQmG59jpONi/nEgoXxb+6Vu8vCVpRw5TUaVgdalVC1GuKghIZMdKVkYRFTjadrJ1hhbYS3X5UNSG/eFMs8l/9KNfOwPMPBFeiOtUI4fbk95Tf6BkSh8TvwlCh6XVcIofJzWTkJQ3crGsIQwWF9JbCC504RPlepS36vlESHTFzbpHmnRDW7BpvWm4rphz6pbM/Kl2Flz8UTCKA4IU9zCKJDguHzjxDYu+bf6RraYo2HeA0anUzUxakmo73LjFiHxmQOkGmdbYj5u5bLBuf+fFVNJ42UaZrbSW/nK/dE=
  template:
    metadata:
      creationTimestamp: null
      name: falcosidekick-splunk
      namespace: falco
    type: Opaque