apiVersion: v1
kind: Secret
metadata:
  name: falcosidekick-splunk
  namespace: falco
  annotations:
    avp.kubernetes.io/path: "secret/data/falco"
type: Opaque
stringData:
  splunk-token: <splunk-token>