apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: yeti-secrets
  namespace: yeti
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: yeti-secrets
    creationPolicy: Owner
  data:
    - secretKey: arangodb-root-password
      remoteRef:
        key: secret/homelab/yeti
        property: arangodb-root-password
    - secretKey: yeti-auth-secret
      remoteRef:
        key: secret/homelab/yeti
        property: auth-secret