---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: yeti-secrets
  namespace: yeti
spec:
  encryptedData:
    arangodb-root-password: AgDBjrpBfUM6llWuiHjKW4LXshNVKUNl/Wie0IhzzZFvNLNWJbv1CO7eqnrr41PxcZnc4fMJZqIXTzKhV/b7zd73EpsTMtbvkIb2wSZTxvR+7Z6UakNfwNCJblMfpVOet8c6Y9FXgRHYuSz+ds3gBMYj5VH/C7Rn+1n3q5HxHlwEfTw92wZP/RvIvSsIAWI7sGRAUM8V3S84EiU9RxTVeHwn25jd/gK7jijNjyPOwG6ryOLpDaGed9VDP9zW1U8lMxFAaAQ671QEjQdSGI1O2+wmG7BXyGmzHwcFCR5r1Jg0VnV6c+8b3kLJ+fAvSUTFJGCUaKZkPqLGGrHMLisPGXV1JK84FBOsYnNPyZBdcBnM+n7LLFOBuqINAV7T3B+2AGEi7f+gmSO9R941zyEmBVwen9wCccATQjAvaeM0DT/P68lCiu+TSlSPvSS2WMOOweID1a4+5CudELYoCzerz8Bi6MwwfLRzAV81cqZ9mJpSwzwy9mlSKpIYF/yQBynhzfKJuqqUsOygWvK2vFmXLfipWFtyqmzLJqf9usLfY9tOCdS0O2lPdv516ZdAd5zGcY5ksWl8goI4/yHpJyscS2PdDEJxe2IOhOOlPoZ5iXzOEtawG5noS5cq6RoznMA7auAQEpb/x7ils+nCRhWXxqLqKVRBXWvd+jh61EEP8d9I1UxJ03mZWScVgckFizPdr+Lb87Th55qX2Kt0
    yeti-auth-secret: AgAl2ZlPyClNnwKPFyV4DolvMudqmNAVwCAXu8dkP9IkdfS8Hyii1MPDBai1A5bX8vnAPK0SLOfirZnzwhGG4viWvFX/K0QPyvdebaz+U0GWELxb1wb9LzXoJw4cELeTxdYlxqxnSM0d5AHOvM0aioS/rsP0Bbd9ayhODfklvWgKb5xUxP3mRCXUmKLZJxHHCu3zx/hoqkO8cDgU1iqpnNm4dpcTM233eZVDRciP2nJ2FcomCBDDBX29JMdKbpiYZ2ZvlFVo1ZaDsGQWUY9hNXzSJzO85RyNKCmi/YY4CRelTVKVM412fLnap5s1+mQa/patfqWYWBcpHX4TaWf3eGNWTQH/5r1b9oim6TFrtvi+dquxfVmOMbptrOeGEDHuz3vivOHPH2HFsD7VICngFh/p4E223lnXLZHaDtI/1/dcWbv9X4CIY+yrrTJmaZenqehsJNFgQHQk7iAUxbbDeSacehu7Wudj+Ba7bjDy4gQHvr9Q3GFYdrJCPzBNJ88BCYpenrkkhNsVx9Mt+WY6u9GqaadMiXX8rZPGLmRyQTAAtWRryN1BIXlCtTHuUGZ7BqaOwhBreIpGZb3zoJJg3XahFurnuIr2ayaXhM32G1uJ8rdfsQukO0NUMA68ArocJuE5K1rTK9Sr7CKt9uIDolL7cFG0LnDVxssy4wK7J2bI9NuUGll6bIuC0n1YCz5eYnDL01E790TpCnDs
  template:
    metadata:
      creationTimestamp: null
      name: yeti-secrets
      namespace: yeti