apiVersion: v1
kind: ConfigMap
metadata:
  name: yeti-config
  namespace: yeti
data:
  YETI_ARANGODB_HOST: "arangodb.yeti.svc.cluster.local"
  YETI_ARANGODB_PORT: "8529"
  YETI_REDIS_BROKER: "redis://redis.yeti.svc.cluster.local:6379/0"
  YETI_REDIS_BACKEND: "redis://redis.yeti.svc.cluster.local:6379/1"