apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: juice-shop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/securecodebox/helm/juice-shop
    chart: juice-shop
    targetRevision: 5.7.0
    helm:
      valuesObject:
        ingress:
          enabled: true
          className: cilium
          annotations:
            cert-manager.io/cluster-issuer: vault-issuer
            cert-manager.io/common-name: juice-shop.homelab.local
          hosts:
            - host: juice-shop.homelab.local
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: juice-shop-tls
              hosts:
                - juice-shop.homelab.local
  destination:
    server: https://kubernetes.default.svc
    namespace: juice-shop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true