apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://codecentric.github.io/helm-charts
    chart: keycloakx
    targetRevision: 7.1.11
    helm:
      valuesObject:
        replicas: 1
        command:
          - "/opt/keycloak/bin/kc.sh"
          - "start"
          - "--http-port=8080"
          - "--hostname-strict=false"
        proxy:
          enabled: false
        http:
          relativePath: "/"
        ingress:
          enabled: true
          ingressClassName: cilium
          annotations:
            cert-manager.io/cluster-issuer: v
            cert-manager.io/common-name: keycloak.homelab.local
          rules:
            - host: keycloak.homelab.local
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - keycloak.homelab.local
              secretName: keycloak-tls
        extraEnv: |
          - name: KEYCLOAK_ADMIN
            value: admin
          - name: KEYCLOAK_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-admin
                key: password
          - name: KC_PROXY_HEADERS
            value: "xforwarded"
          - name: KC_HOSTNAME
            value: "keycloak.homelab.local"
          - name: KC_HTTP_ENABLED
            value: "true"
          - name: KC_HOSTNAME_STRICT
            value: "false"
          - name: KC_DB
            value: postgres
          - name: KC_DB_URL
            value: jdbc:postgresql://keycloak-postgres-postgresql:5432/keycloak #gitleaks:allow
          - name: KC_DB_USERNAME
            value: keycloak
          - name: KC_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-postgres
                key: password
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true