apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubescape-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubescape.github.io/helm-charts/
    chart: kubescape-operator
    targetRevision: 1.40.2
    helm:
      values: |
        clusterName: homelab
        kubescape:
          submit: false
          downloadArtifacts: true
        kubescapeScheduler:
          enabled: true
          scanSchedule: "0 0 * * *"
        kubevuln:
          enabled: true
        kubevulnScheduler:
          enabled: true
          scanSchedule: "0 0 * * *"
  destination:
    server: https://kubernetes.default.svc
    namespace: kubescape
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true