apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubescape
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubescape.github.io/helm-charts/
    chart: kubescape-operator
    targetRevision: "1.40.2"
    helm:
      valuesObject:
        clusterName: homelab

        kubescape:
          submit: false

        kubescapeScheduler:
          enabled: true
          scanSchedule: "0 */4 * * *"

        kubevulnScheduler:
          enabled: true
          scanSchedule: "0 */4 * * *"

        capabilities:
          continuousScan: enable
          prometheusExporter: enable
          runtimeDetection: enable
          vulnerabilityScan: enable
          configurationScan: enable

        nodeAgent:
          config:
            prometheusExporter: enable
          serviceMonitor:
            enabled: true
            labels:
              release: kube-prometheus-stack

  destination:
    server: https://kubernetes.default.svc
    namespace: kubescape
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true