apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: splunk-otel-collector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://signalfx.github.io/splunk-otel-collector-chart
    chart: splunk-otel-collector
    targetRevision: 0.152.0
    helm:
      valuesObject:
        clusterName: "homelab"
        secret:
          create: false
          name: splunk-otel-secret
        splunkPlatform:
          endpoint: https://splunk-splunk-standalone-service.splunk.svc.cluster.local:8088
          index: "main"
          insecureSkipVerify: true
        logsEngine: otel
        logsCollection:
          containers:
            enabled: true
          journald:
            enabled: true
        clusterReceiver:
          enabled: true
        agent:
          enabled: true
          config:
            processors:
              filter/security_namespaces:
                logs:
                  include:
                    match_type: strict
                    resource_attributes:
                      - key: k8s.namespace.name
                        value: falco
                      - key: k8s.namespace.name
                        value: keycloak
                      - key: k8s.namespace.name
                        value: tetragon
                      - key: k8s.namespace.name
                        value: splunk
              transform/index_routing:
                log_statements:
                  - context: log
                    statements:
                      - set(resource.attributes["com.splunk.index"], "falco") where resource.attributes["k8s.namespace.name"] == "falco"
                      - set(resource.attributes["com.splunk.index"], "keycloak-auth") where resource.attributes["k8s.namespace.name"] == "keycloak"
                      - set(resource.attributes["com.splunk.index"], "tetragon") where resource.attributes["k8s.namespace.name"] == "tetragon"
            service:
              pipelines:
                logs:
                  processors:
                    - memory_limiter
                    - filter/security_namespaces
                    - transform/index_routing
                    - batch
                    - resourcedetection
                    - resource
                    - resource/logs
  destination:
    server: https://kubernetes.default.svc
    namespace: splunk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true