apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: splunk-enterprise
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://splunk.github.io/splunk-operator
    chart: splunk-enterprise
    targetRevision: 3.1.0
    helm:
      valuesObject:
        splunk-operator:
          enabled: false
        standalone:
          enabled: true
          name: splunk
          extraEnv:
            - name: SPLUNK_GENERAL_TERMS
              value: "--accept-sgt-current-at-splunk-com"
          resources:
            requests:
              cpu: 250m
              memory: 2Gi
            limits:
              cpu: "1"
              memory: 3Gi
          etcVolumeStorageConfig:
            storageCapacity: 5Gi
          varVolumeStorageConfig:
            storageCapacity: 20Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: splunk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true