apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: splunk-otel-collector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://signalfx.github.io/splunk-otel-collector-chart
    chart: splunk-otel-collector
    targetRevision: 0.152.0
    helm:
      valuesObject:
        clusterName: "homelab"
        secret:
          create: false
          name: splunk-otel-secret
        splunkPlatform:
          endpoint: https://splunk-splunk-standalone-service.splunk.svc.cluster.local:8088
          insecureSkipVerify: true
          index: main
        logsEngine: otel
        logsCollection:
          containers:
            enabled: true
          journald:
            enabled: true
          extraFileLogs:
            filelog/k8s-audit:
              include:
                - /var/log/kubernetes/audit.log
              start_at: end
              operators:
                - type: json_parser
              resource:
                com.splunk.sourcetype: "kube:apiserver:audit"
                com.splunk.index: "k8s-audit"
        clusterReceiver:
          enabled: true
        agent:
          enabled: true
          extraVolumes:
            - name: k8s-audit-log
              hostPath:
                path: /var/log/kubernetes
                type: DirectoryOrCreate
          extraVolumeMounts:
            - name: k8s-audit-log
              mountPath: /var/log/kubernetes
              readOnly: true
  destination:
    server: https://kubernetes.default.svc
    namespace: splunk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true