apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: splunk-otel-collector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://signalfx.github.io/splunk-otel-collector-chart
    chart: splunk-otel-collector
    targetRevision: 0.152.0
    helm:
      valuesObject:
        secret:
          create: false
          name: splunk-otel-secret
        splunkPlatform:
          endpoint: https://splunk-hec.homelab.local
          index: "main"
          insecureSkipVerify: true
        logsEngine: otel
        logsCollection:
          containers:
            enabled: true
          journald:
            enabled: true
        splunkObservability:
          enabled: false
        clusterReceiver:
          enabled: true
        agent:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: splunk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true