apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: zap
  name: zap-config
  namespace: zap-demo
data:
  af-plan.yaml: |
    env:
      contexts:
      - authentication:
          parameters: {}
          verification:
            method: response
            pollFrequency: 60
            pollUnits: seconds
        includePaths:
        - http://juice-shop.juice-shop.svc.cluster.local:3000.*
        name: Default Context
        sessionManagement:
          method: cookie
          parameters: {}
        technology:
          exclude: []
        urls:
        - http://juice-shop.juice-shop.svc.cluster.local:3000
      parameters:
        failOnError: false
        failOnWarning: false
        progressToStdout: true
      vars: {}
    jobs:
    - name: spider
      type: spider
      parameters:
        context: Default Context
        url: http://juice-shop.juice-shop.svc.cluster.local:3000
        maxDuration: 5
    - name: activeScan
      type: activeScan
      parameters:
        context: Default Context
        maxAlertsPerRule: 0
        maxRuleDurationInMins: 0
        maxScanDurationInMins: 2
        policy: ""
        threadPerHost: 2
        user: ""
      policyDefinition:
        defaultStrength: medium
        defaultThreshold: medium
        rules: []
    - name: json-report
      type: report
      parameters:
        template: traditional-json
        reportDir: /tmp
        reportFile: zap-report
        reportTitle: ZAP Scanning Report
        reportDescription: ""
        displayReport: false
      risks:
      - high
      confidences:
      - medium
      - high
      - confirmed
      sites: []